package com.team1.f1_api.model;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for the {@link FastestLap} entity.
 * Verifies constructor initialization, getter methods, and entity relationships.
 */
class FastestLapTest {

    @Test
    void testDefaultConstructor() {
        FastestLap lap = new FastestLap();
        assertNull(lap.getLapId());
        assertNull(lap.getTrack());
        assertNull(lap.getVehicle());
        assertNull(lap.getLapTime());
        assertNull(lap.getDriver());
    }

    @Test
    void testParameterizedConstructor() {
        Track track = new Track("AU", "Australia", "Albert Park", "Full Circuit", 5.278);
        Vehicle vehicle = new Vehicle("McLaren MCL39");
        FastestLap lap = new FastestLap(track, vehicle, "1:15.10", "Lando Norris");

        assertNull(lap.getLapId()); // ID is auto-generated by DB
        assertSame(track, lap.getTrack());
        assertSame(vehicle, lap.getVehicle());
        assertEquals("1:15.10", lap.getLapTime());
        assertEquals("Lando Norris", lap.getDriver());
    }

    @Test
    void testTrackRelationship() {
        Track track = new Track("EU", "Belgium", "Zolder", "Full Circuit", 3.98);
        Vehicle vehicle = new Vehicle("Ferrari SF25");
        FastestLap lap = new FastestLap(track, vehicle, "1:40.26", "Charles Leclerc");

        assertEquals("Zolder", lap.getTrack().getName());
        assertEquals("Belgium", lap.getTrack().getCountry());
    }

    @Test
    void testVehicleRelationship() {
        Track track = new Track("AU", "Australia", "Albert Park", "Full Circuit", 5.278);
        Vehicle vehicle = new Vehicle("Red Bull RB21");
        FastestLap lap = new FastestLap(track, vehicle, "1:15.48", "Max Verstappen");

        assertEquals("Red Bull RB21", lap.getVehicle().getName());
    }
}
