package com.team1.f1_api.model;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for the {@link Track} entity.
 * Verifies constructor initialization and getter methods.
 */
class TrackTest {

    @Test
    void testDefaultConstructor() {
        Track track = new Track();
        assertNull(track.getTrackId());
        assertNull(track.getRegion());
        assertNull(track.getCountry());
        assertNull(track.getName());
        assertNull(track.getLayout());
        assertNull(track.getLengthKm());
    }

    @Test
    void testParameterizedConstructor() {
        Track track = new Track("AU", "Australia", "Albert Park", "Full Circuit", 5.278);

        assertNull(track.getTrackId()); // ID is auto-generated by DB
        assertEquals("AU", track.getRegion());
        assertEquals("Australia", track.getCountry());
        assertEquals("Albert Park", track.getName());
        assertEquals("Full Circuit", track.getLayout());
        assertEquals(5.278, track.getLengthKm());
    }

    @Test
    void testConstructorWithNullLength() {
        Track track = new Track("EU", "Belgium", "Zolder", "Full Circuit", null);

        assertEquals("EU", track.getRegion());
        assertEquals("Belgium", track.getCountry());
        assertEquals("Zolder", track.getName());
        assertEquals("Full Circuit", track.getLayout());
        assertNull(track.getLengthKm());
    }
}
