package com.team1.f1_api.model;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for the {@link Vehicle} entity.
 * Verifies constructor initialization and getter methods.
 */
class VehicleTest {

    @Test
    void testDefaultConstructor() {
        Vehicle vehicle = new Vehicle();
        assertNull(vehicle.getVehicleId());
        assertNull(vehicle.getName());
    }

    @Test
    void testParameterizedConstructor() {
        Vehicle vehicle = new Vehicle("McLaren MCL39");

        assertNull(vehicle.getVehicleId()); // ID is auto-generated by DB
        assertEquals("McLaren MCL39", vehicle.getName());
    }
}
